# Generated by Django 3.0.6 on 2020-06-05 22:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='justification',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
