# Generated by Django 3.0.9 on 2020-08-27 01:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20200605_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='justification',
            field=tinymce.models.HTMLField(),
        ),
    ]
