# Generated by Django 3.0.1 on 2020-04-27 20:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Codigo do curso')),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'Started'), (2, 'Finished')], default=0, verbose_name='Progress')),
            ],
            options={
                'verbose_name': 'Progresso no Curso',
                'verbose_name_plural': 'Progressos nos Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseWatchedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('TEXT', 'Text'), ('FILE', 'File'), ('CODE', 'Code')], max_length=6)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Codigo da inscrição')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=0, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PathProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Codigo do curso')),
                ('status', models.IntegerField(choices=[(0, 'Queued'), (1, 'Started'), (2, 'Finished')], default=0, verbose_name='Progress')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollments.PathEnrollment')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Path', verbose_name='Path')),
            ],
            options={
                'verbose_name': 'Progresso na Trilha',
                'verbose_name_plural': 'Progressos nas Trilhas',
            },
        ),
    ]
