# Generated by Django 3.0.1 on 2020-04-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200429_1021'),
        ('enrollments', '0002_auto_20200427_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursewatchedcontent',
            unique_together={('course_progress', 'content')},
        ),
        migrations.RemoveField(
            model_name='coursewatchedcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='coursewatchedcontent',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='coursewatchedcontent',
            name='object_id',
        ),
    ]
