# Generated by Django 3.0.6 on 2020-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_auto_20200506_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
