# Generated by Django 3.1 on 2020-08-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_courseprogress_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
