# Generated by Django 3.0.5 on 2020-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='nome completo', max_length=30, verbose_name='NOME COMPLETO'),
            preserve_default=False,
        ),
    ]
