# Generated by Django 3.0.1 on 2020-04-27 20:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Certificado de Curso',
                'verbose_name_plural': 'Certificados de Cursos',
            },
        ),
        migrations.CreateModel(
            name='PathCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Certificado de Trilha',
                'verbose_name_plural': 'Certificados de Trilhas',
            },
        ),
    ]
