# Generated by Django 3.0.6 on 2020-05-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_usercertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercertificate',
            old_name='course',
            new_name='enrollment',
        ),
    ]
