# Generated by Django 3.0.6 on 2020-05-29 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20200528_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificate',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='certificate_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
