# Generated by Django 3.0.6 on 2020-05-31 12:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20200529_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificate',
            name='file',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='text',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
