# Generated by Django 3.0.1 on 2020-04-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200427_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='object_id',
        ),
    ]
