# Generated by Django 3.0.6 on 2020-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200429_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Aguardando Moderação'), (2, 'Aprovado'), (3, 'Reprovado')], default=1),
        ),
    ]
