# Generated by Django 3.0.6 on 2020-05-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoda_emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuserscourse',
            options={'verbose_name': 'Enviar Email para Alunos', 'verbose_name_plural': 'Enviar Email para Alunos'},
        ),
    ]
