version: '3'

services:
  api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.prod
    env_file:
      - ".env.prod"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8080
  
  nginx_api:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8080:8080
    depends_on:
      - api

volumes:
  static_volume:
  media_volume: