# Generated by Django 3.0.1 on 2020-04-29 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200427_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='code',
            name='title',
        ),
        migrations.RemoveField(
            model_name='file',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='text',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
