# Generated by Django 3.0.6 on 2020-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200429_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathcourse',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
