# Generated by Django 3.0.6 on 2020-05-29 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursereview_pathreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 estrelas')], default=5),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pathreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 estrelas')], default=5),
        ),
        migrations.AddField(
            model_name='pathreview',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pathreview',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
