# Generated by Django 3.0.6 on 2020-05-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200529_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='request_avaliation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pathreview',
            name='request_avaliation',
            field=models.BooleanField(default=True),
        ),
    ]
