# Generated by Django 3.0.9 on 2020-08-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200529_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathreview',
            name='path',
        ),
        migrations.RemoveField(
            model_name='pathreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
        migrations.DeleteModel(
            name='PathReview',
        ),
    ]
